graph TD
rootNode["proyecto"]
 --> MermaidFolderStructure_java["MermaidFolderStructure.java"]
 --> ProyectoApplication_java["ProyectoApplication.java"]
 --> v1
v1 --> v1_assemblers
v1 --> v1_bootstrap
v1 --> v1_config
v1_config --> v1_config_otherconifg
v1_config --> v1_config_swagger
v1_config_swagger --> v1_config_swagger_SwaggerConfig_java["SwaggerConfig.java"]
v1 --> v1_controllers
v1_controllers --> v1_controllers_producto
v1_controllers --> v1_controllers_usuario
v1_controllers_usuario --> v1_controllers_usuario_UsuarioController_java["UsuarioController.java"]
v1_controllers_usuario --> v1_controllers_usuario_UsuarioModelAssembler_java["UsuarioModelAssembler.java"]
v1 --> v1_domain
v1_domain --> v1_domain_Rol_java["Rol.java"]
v1_domain --> v1_domain_TipoUsuario_java["TipoUsuario.java"]
v1_domain --> v1_domain_Usuario_java["Usuario.java"]
v1 --> v1_dto
v1_dto --> v1_dto_requests
v1_dto --> v1_dto_responses
v1_dto_responses --> v1_dto_responses_UsuarioDTO_java["UsuarioDTO.java"]
v1 --> v1_exceptions
v1_exceptions --> v1_exceptions_GlobalExceptionHandler_java["GlobalExceptionHandler.java"]
v1_exceptions --> v1_exceptions_messages
v1_exceptions --> v1_exceptions_usuario
v1_exceptions_usuario --> v1_exceptions_usuario_DuplicateUserException_java["DuplicateUserException.java"]
v1_exceptions_usuario --> v1_exceptions_usuario_UserNotFoundException_java["UserNotFoundException.java"]
v1_exceptions_usuario --> v1_exceptions_usuario_UUIDInvalid_java["UUIDInvalid.java"]
v1 --> v1_mapping
v1 --> v1_repositories
v1_repositories --> v1_repositories_producto
v1_repositories --> v1_repositories_usuario
v1_repositories_usuario --> v1_repositories_usuario_IUsuarioRepository_java["IUsuarioRepository.java"]
v1 --> v1_requests_handler
v1 --> v1_security
v1 --> v1_services
v1_services --> v1_services_producto
v1_services --> v1_services_usuario
v1_services_usuario --> v1_services_usuario_impl
v1_services_usuario_impl --> v1_services_usuario_impl_UsuarioServicieImpl_java["UsuarioServicieImpl.java"]
v1_services_usuario --> v1_services_usuario_IUsuarioService_java["IUsuarioService.java"]
v1 --> v1_utils
