name: Java CI with Maven, MySQL & Redis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: sport_ecommerce_db_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Wait for MySQL
        run: |
          for i in {1..15}; do
            if mysqladmin ping -h 127.0.0.1 -P 3306 --protocol=tcp -uroot -proot --silent; then
              echo "MySQL is up!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Build with Maven
        #run: cd sportecommerce && mvn -B clean package --file pom.xml -DskipTests
        run: cd sportecommerce && mvn -B clean package --file pom.xml

      - name: Run Tests
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/sport_ecommerce_db_test
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root
          SPRING_REDIS_HOST: 127.0.0.1
          SPRING_REDIS_PORT: 6379
        run: cd sportecommerce && mvn test -Dspring.profiles.active=test

      - name: Upload coverage to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          curl -Ls https://coverage.codacy.com/get.sh | bash
          REPORTER=$(ls ~/.cache/codacy/coverage-reporter/*/codacy-coverage-reporter)
          $REPORTER report -l Java -r sportecommerce/target/site/jacoco/jacoco.xml

  deploy:
    needs: build-test
    if: ${{ success() }}
    uses: ./.github/workflows/Deploy.yml
